# https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux 
files:
  - source: /
    destination: /app
hooks:
  AfterInstall:
    - location: /app/scripts/stop.sh
      timeout: 30
  ApplicationStart:
    - location: /app/scripts/start.sh
      timeout: 30 