version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn
  pre_build:
    commands:
      - git config --global user.email "petersonvgama@gmail.com"
      - git config --global user.name "Serenity - CodeBuild"
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - git checkout main
      - yarn version --patch
      - export VERSION=`yarn --silent current-version`
      - zip -r -q build.zip bin/ node_modules/ scripts/ package.json .env-cmdrc appspec.yml buildspec.yml
      - git push origin HEAD:main --tags
artifacts:
  files:
    - build.zip
  name: guanabara_status_be/${VERSION}